### ISSUE TITLE
2D Data

### ISSUE THREAD

**Issue by krekiehn** [MIC-DKFZ/nnUNet#562]
We work with 2D Data. Projections from 3D CT Data. These arrays we put in our version of "convert_2d_image_to_nifti". So we get pseudo 3D nii.gz line in the Task120 example.

nnUNet_plan_and_preprocess -t 334 -pl3d None 
works fine.

nnUNet_train 2d nnUNetTrainerV2 334 0

gives the following Error:

epoch:  0
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py37/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/code/nnUNet/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/code/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 442, in run_training
    ret = super().run_training()
  File "/code/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 319, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 455, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/code/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 247, in run_iteration
    output = self.network(data)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/nnUNet/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/nnUNet/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/nnUNet/nnunet/network_architecture/generic_UNet.py", line 68, in forward
    return self.lrelu(self.instnorm(x))
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/instancenorm.py", line 57, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 2080, in instance_norm
    use_input_stats, momentum, eps, torch.backends.cudnn.enabled
IndexError: select(): index 0 out of range for tensor of size [0] at dimension 0

Before we get following print():

###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'X-Ray'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 0, 'num_pool_per_axis': [6, 5], 'patch_size': array([320, 192]), 'median_patient_size_in_voxels': array([  1, 295, 161]), 'current_spacing': array([999.,   1.,   1.]), 'original_spacing': array([999.,   1.,   1.]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 1]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /code/nnUNet_raw_base/nnUNet_preprocessed/Task334_VERSE_PROJECTION/nnUNetData_plans_v2.1_2D
###############################################
loading dataset
loading all case properties
2021-03-18 14:40:47.924273: Using splits from existing split file: /code/nnUNet_raw_base/nnUNet_preprocessed/Task334_VERSE_PROJECTION/splits_final.pkl
2021-03-18 14:40:47.924600: The split file contains 5 splits.
2021-03-18 14:40:47.924650: Desired fold for training: 0
2021-03-18 14:40:47.924693: This split has 8 training and 3 validation cases.
unpacking dataset
done
2021-03-18 14:40:52.146127: lr: 0.01
using pin_memory on device 0
using pin_memory on device 0
2021-03-18 14:40:53.604584: Unable to plot network architecture:
2021-03-18 14:40:53.604795: No module named 'hiddenlayer'
2021-03-18 14:40:53.604853:
printing the network instead:

Is batch_size 0 a problem?
Images don't have all same shape, is that a problem?

**Comment by FabianIsensee** [comment]
Yes that's got to be it. I don't know how this happened, though. Would you mind sharing the data so that I can reproduce it?

**Comment by krekiehn** [comment]
sure:

https://cloud.rz.uni-kiel.de/index.php/s/64sYYcCQGALM9GP

**Comment by krekiehn** [comment]
sure:

https://cloud.rz.uni-kiel.de/index.php/s/aHWrs97NxjZgNMk

**Comment by FabianIsensee** [comment]
this is the cropped data. I need the raw one :-)

**Comment by krekiehn** [comment]
oh sorry, next try:

https://cloud.rz.uni-kiel.de/index.php/s/PDc5PybYfczg3sE

**Comment by FabianIsensee** [comment]
Yup there was a bug where the batch size could get 0 when the dataset was VERY small. It is now fixed in the current master.
Your dataset has only very few cases. I would be surprised if nnU-Net (or any other U-Net based tool) can properly learn from it

**Comment by krekiehn** [comment]
thank you very much for you fast response!

you are absolutely right, this is a very small dataset. but it is just a test dataset für trying out the data conversion and nnUNet pipeline. 

How can I install the new master? I try "git pull" and get an update but still have the same error.

git pull
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 26 (delta 11), reused 24 (delta 9), pack-reused 0
Unpacking objects: 100% (26/26), done.
From https://github.com/MIC-DKFZ/nnUNet
   ef9d453..2080401  master     -> origin/master
Updating ef9d453..2080401
Fast-forward
 .../alternative_experiment_planning/experiment_planner_baseline_3DUNet_v21_11GB.py                  |  2 +-
 .../alternative_experiment_planning/experiment_planner_baseline_3DUNet_v21_32GB.py                  |  2 +-
 .../experiment_planning/alternative_experiment_planning/experiment_planner_residual_3DUNet_v21.py   |  2 +-
 .../alternative_experiment_planning/patch_size/experiment_planner_3DUNet_isotropic_in_mm.py         |  2 +-
 .../alternative_experiment_planning/patch_size/experiment_planner_3DUNet_isotropic_in_voxels.py     |  2 +-
 .../pooling_and_convs/experiment_planner_baseline_3DUNet_allConv3x3.py                              |  2 +-
 .../pooling_and_convs/experiment_planner_baseline_3DUNet_poolBasedOnSpacing.py                      |  2 +-
 nnunet/experiment_planning/experiment_planner_baseline_2DUNet.py                                    |  2 +-
 nnunet/experiment_planning/experiment_planner_baseline_2DUNet_v21.py                                |  2 +-
 nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py                                    |  2 +-
 nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py                                |  2 +-
 nnunet/training/network_training/nnUNet_variants/{profiling => benchmarking}/__init__.py            |  0
 .../network_training/nnUNet_variants/{profiling => benchmarking}/nnUNetTrainerV2_2epochs.py         |  0
 .../network_training/nnUNet_variants/{profiling => benchmarking}/nnUNetTrainerV2_dummyLoad.py       | 10 +++++++++-
 14 files changed, 20 insertions(+), 12 deletions(-)
 rename nnunet/training/network_training/nnUNet_variants/{profiling => benchmarking}/__init__.py (100%)
 rename nnunet/training/network_training/nnUNet_variants/{profiling => benchmarking}/nnUNetTrainerV2_2epochs.py (100%)
 rename nnunet/training/network_training/nnUNet_variants/{profiling => benchmarking}/nnUNetTrainerV2_dummyLoad.py (90%)
(py37)

ERROR:

stage:  0
{'batch_size': 0, 'num_pool_per_axis': [6, 5], 'patch_size': array([320, 192]), 'median_patient_size_in_voxels': array([  1, 295, 161]), 'current_spacing': array([999.,   1.,   1.]), 'original_spacing': array([999.,   1.,   1.]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 1]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

IndexError: select(): index 0 out of range for tensor of size [0] at dimension 0


Do I have to delete the nnUNet folder and reinstall it?
Of course, I can try it with the total dataset.

**Comment by FabianIsensee** [comment]
You need to rerun nnUNet_plan_and_preprocess after updating. Sorry.I forgot to mention that.
Best,
Fabian

**Comment by krekiehn** [comment]
No Problem. I should have thought of that by myself. Thank you very much for your help! Now it works.
